CREATE TABLE IF NOT EXISTS households (id uuid PRIMARY KEY, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS invitations (code VARCHAR(6) PRIMARY KEY, household_id uuid NOT NULL, granted_role VARCHAR(20) NOT NULL, CONSTRAINT fk_invitations_household_id__id FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX invitations_household_id ON invitations (household_id);
CREATE TABLE IF NOT EXISTS products (id uuid PRIMARY KEY, household_id uuid NOT NULL, "name" VARCHAR(60) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_products_household_id__id FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX products_household_id ON products (household_id);
CREATE TABLE IF NOT EXISTS residents (id uuid PRIMARY KEY, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS stock_movements (id BIGSERIAL PRIMARY KEY, product_id uuid NOT NULL, kind VARCHAR(20) NOT NULL, quantity INT NOT NULL, occurred_at TIMESTAMP NOT NULL, actor_resident_id uuid NOT NULL, note VARCHAR(255) NOT NULL, target_movement_id BIGINT NULL, reason VARCHAR(255) NULL);
CREATE INDEX stock_movements_product_id_id ON stock_movements (product_id, id);
CREATE TABLE IF NOT EXISTS resident_display_names (id BIGSERIAL PRIMARY KEY, resident_id uuid NOT NULL, display_name VARCHAR(100) NOT NULL, recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_resident_display_names_resident_id__id FOREIGN KEY (resident_id) REFERENCES residents(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX resident_display_names_resident_id_id ON resident_display_names (resident_id, id);
CREATE TABLE IF NOT EXISTS catalog_items (id uuid PRIMARY KEY, jan VARCHAR(13) NOT NULL, "name" VARCHAR(60) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
ALTER TABLE catalog_items ADD CONSTRAINT catalog_items_jan_unique UNIQUE (jan);
CREATE TABLE IF NOT EXISTS household_membership_events (id BIGSERIAL PRIMARY KEY, household_id uuid NOT NULL, resident_id uuid NOT NULL, "role" VARCHAR(20) NOT NULL, status VARCHAR(10) NOT NULL, recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_household_membership_events_household_id__id FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_household_membership_events_resident_id__id FOREIGN KEY (resident_id) REFERENCES residents(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX household_membership_events_household_id_resident_id_id ON household_membership_events (household_id, resident_id, id);
CREATE INDEX household_membership_events_resident_id_household_id_id ON household_membership_events (resident_id, household_id, id);
CREATE TABLE IF NOT EXISTS invitation_validity_events (id BIGSERIAL PRIMARY KEY, invitation_code VARCHAR(6) NOT NULL, validity VARCHAR(10) NOT NULL, recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_invitation_validity_events_invitation_code__code FOREIGN KEY (invitation_code) REFERENCES invitations(code) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX invitation_validity_events_invitation_code_id ON invitation_validity_events (invitation_code, id);
CREATE TABLE IF NOT EXISTS product_catalog_links (product_id uuid PRIMARY KEY, catalog_item_id uuid NOT NULL, CONSTRAINT fk_product_catalog_links_product_id__id FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_product_catalog_links_catalog_item_id__id FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX product_catalog_links_catalog_item_id ON product_catalog_links (catalog_item_id);
CREATE TABLE IF NOT EXISTS product_wanted_events (id BIGSERIAL PRIMARY KEY, product_id uuid NOT NULL, wanted BOOLEAN NOT NULL, recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_product_wanted_events_product_id__id FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX product_wanted_events_product_id_id ON product_wanted_events (product_id, id);
CREATE TABLE IF NOT EXISTS product_revisions (id BIGSERIAL PRIMARY KEY, product_id uuid NOT NULL, unit VARCHAR(10) NOT NULL, minimum_stock INT NOT NULL, image_ref VARCHAR(512) NULL, status VARCHAR(20) NOT NULL, recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_product_revisions_product_id__id FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX product_revisions_product_id_id ON product_revisions (product_id, id);
CREATE TABLE IF NOT EXISTS resident_auth_identities (id BIGSERIAL PRIMARY KEY, resident_id uuid NOT NULL, provider VARCHAR(20) NOT NULL, subject VARCHAR(255) NOT NULL, linked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_resident_auth_identities_resident_id__id FOREIGN KEY (resident_id) REFERENCES residents(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
ALTER TABLE resident_auth_identities ADD CONSTRAINT resident_auth_identities_provider_subject_unique UNIQUE (provider, subject);
CREATE INDEX resident_auth_identities_resident_id ON resident_auth_identities (resident_id);
CREATE TABLE IF NOT EXISTS household_names (id BIGSERIAL PRIMARY KEY, household_id uuid NOT NULL, "name" VARCHAR(30) NOT NULL, recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_household_names_household_id__id FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX household_names_household_id_id ON household_names (household_id, id);
CREATE TABLE IF NOT EXISTS product_barcodes (product_id uuid PRIMARY KEY, jan VARCHAR(13) NOT NULL, CONSTRAINT fk_product_barcodes_product_id__id FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
ALTER TABLE stock_movements ADD CONSTRAINT fk_stock_movements_product_id__id FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE stock_movements ADD CONSTRAINT fk_stock_movements_actor_resident_id__id FOREIGN KEY (actor_resident_id) REFERENCES residents(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE stock_movements ADD CONSTRAINT fk_stock_movements_target_movement_id__id FOREIGN KEY (target_movement_id) REFERENCES stock_movements(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
CREATE SEQUENCE IF NOT EXISTS stock_movements_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS resident_display_names_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS household_membership_events_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS invitation_validity_events_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS product_wanted_events_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS product_revisions_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS resident_auth_identities_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS household_names_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;