#!/bin/sh
# Garage をローカル用に宣言的セットアップする(compose up 時に garage-init が実行)。
# - layout(1 ノード・容量割当)を確定
# - bucket `mindstock-images`
# - access key `mindstock-key`(read/write/owner 権限を bucket に付与)
# 生成された STORAGE_* を /output/.env.garage に書き出す。冪等(再実行で既存を再利用)。
#
# dxflrs/garage は scratch イメージで shell を持たないため、本スクリプトは alpine で
# 動かし garage の admin API(:3903)を curl 越しに叩く(zitadel-init と同じ方式)。
set -eu

ADMIN="http://garage:3903"
TOKEN="localadmintoken"
BUCKET="mindstock-images"
KEY="mindstock-key"
OUT="/output/.env.garage"

echo "[garage-init] installing curl/jq ..."
apk add --no-cache curl jq >/dev/null

# $1=METHOD $2=PATH(?query 含む) $3=BODY(任意)
api() {
  if [ "$#" -ge 3 ]; then
    curl -fsS -X "$1" "$ADMIN$2" -H "Authorization: Bearer $TOKEN" \
      -H "Content-Type: application/json" -d "$3"
  else
    curl -fsS -X "$1" "$ADMIN$2" -H "Authorization: Bearer $TOKEN"
  fi
}

echo "[garage-init] waiting for garage admin API ..."
i=0
until api GET /v2/GetClusterStatus >/dev/null 2>&1; do
  i=$((i + 1)); [ "$i" -gt 60 ] && { echo "[garage-init] garage not ready, abort"; exit 1; }
  sleep 2
done

# --- layout ---
# 既にロールが割り当て済みなら何もしない(冪等)。未割り当てなら staged role を
# 投入して次バージョンへ apply する。capacity はバイト指定(1GB)。
NODE_ID="$(api GET /v2/GetClusterStatus | jq -r '.nodes[0].id')"
ROLE="$(api GET /v2/GetClusterLayout | jq -r --arg id "$NODE_ID" '.roles[] | select(.id==$id) | .id')"
if [ -z "$ROLE" ]; then
  CUR_VER="$(api GET /v2/GetClusterLayout | jq -r '.version')"
  NEXT_VER="$((CUR_VER + 1))"
  api POST /v2/UpdateClusterLayout \
    "{\"roles\":[{\"id\":\"$NODE_ID\",\"zone\":\"dc1\",\"capacity\":1000000000,\"tags\":[]}]}" >/dev/null
  api POST /v2/ApplyClusterLayout "{\"version\":$NEXT_VER}" >/dev/null
  echo "[garage-init] assigned layout (v$NEXT_VER) to $NODE_ID"
else
  echo "[garage-init] reuse layout for $NODE_ID"
fi

# --- bucket ---
BID="$(api GET "/v2/GetBucketInfo?globalAlias=$BUCKET" 2>/dev/null | jq -r '.id // empty')"
if [ -z "$BID" ]; then
  BID="$(api POST /v2/CreateBucket "{\"globalAlias\":\"$BUCKET\"}" | jq -r '.id')"
  echo "[garage-init] created bucket $BUCKET = $BID"
else
  echo "[garage-init] reuse bucket $BUCKET = $BID"
fi

# --- access key ---
# CreateKey は毎回新しいキーを発行してしまうため、既存があれば再利用する。
AK="$(api GET /v2/ListKeys | jq -r --arg n "$KEY" '.[] | select(.name==$n) | .id' | head -n1)"
if [ -z "$AK" ]; then
  AK="$(api POST /v2/CreateKey "{\"name\":\"$KEY\"}" | jq -r '.accessKeyId')"
  echo "[garage-init] created key $KEY = $AK"
else
  echo "[garage-init] reuse key $KEY = $AK"
fi
# 応答を一度変数に受けてから jq する(curl 失敗を空値として握り潰さない。
# `api` は curl -f なので 5xx/通信断は非ゼロ終了し set -e で中断する)。
KEYINFO="$(api GET "/v2/GetKeyInfo?id=$AK&showSecretKey=true")"
SK="$(printf '%s' "$KEYINFO" | jq -r '.secretAccessKey')"

# 致命: bucket/access/secret が空のまま .env.garage を書くと後段が静かに壊れるので明示的に弾く。
if [ -z "$BID" ] || [ -z "$AK" ] || [ -z "$SK" ] || [ "$SK" = "null" ]; then
  echo "[garage-init] ERROR: empty bucket/access/secret (BID=${BID:+set} AK=${AK:+set} SK=${SK:+set}); aborting"
  exit 1
fi

# --- bucket への権限付与(冪等: 何度叩いても同じ状態に収束) ---
api POST /v2/AllowBucketKey \
  "{\"bucketId\":\"$BID\",\"accessKeyId\":\"$AK\",\"permissions\":{\"read\":true,\"write\":true,\"owner\":true}}" >/dev/null

# --- 書き出し ---
cat > "$OUT" <<EOF
# generated by docker/garage-init.sh on \`docker compose up\` — DO NOT edit by hand.
STORAGE_ENDPOINT=http://localhost:3900
STORAGE_REGION=garage
STORAGE_BUCKET=$BUCKET
STORAGE_ACCESS_KEY=$AK
STORAGE_SECRET_KEY=$SK
EOF

# 資格情報はログに残さない(docker compose logs に平文で出さない)。
echo "[garage-init] wrote $OUT (bucket=$BUCKET; credentials hidden)"
echo "[garage-init] done."
