#!/bin/sh
# Zitadel をローカル用に宣言的セットアップする(compose up 時に zitadel-init が実行)。
# - Project `mindstock`
# - API app `mindstock-backend`(JWT 検証用。aud に乗る)
# - PKCE app `mindstock-frontend`(DevMode + AccessTokenType=JWT + redirect URI)
# 生成された AUTH_* を /output/.env.zitadel に書き出す。冪等(再実行で既存を再利用)。
set -eu

ZITADEL="http://zitadel:8080"   # コンテナ内部。instance は Host ヘッダで解決する
HOST="localhost:8081"           # ExternalDomain:ExternalPort と一致させる
PAT_FILE="/machinekey/pat.txt"
OUT="/output/.env.zitadel"

echo "[zitadel-init] installing curl/jq ..."
apk add --no-cache curl jq >/dev/null

echo "[zitadel-init] waiting for service-account PAT ($PAT_FILE) ..."
i=0
while [ ! -s "$PAT_FILE" ]; do
  i=$((i + 1)); [ "$i" -gt 90 ] && { echo "[zitadel-init] PAT not found, abort"; exit 1; }
  sleep 2
done
PAT="$(cat "$PAT_FILE")"

# $1=METHOD $2=PATH $3=BODY(任意)
api() {
  if [ "$#" -ge 3 ]; then
    curl -fsS -X "$1" "$ZITADEL$2" -H "Host: $HOST" \
      -H "Authorization: Bearer $PAT" -H "Content-Type: application/json" -d "$3"
  else
    curl -fsS -X "$1" "$ZITADEL$2" -H "Host: $HOST" \
      -H "Authorization: Bearer $PAT" -H "Content-Type: application/json"
  fi
}

echo "[zitadel-init] waiting for management API ..."
i=0
until api GET /management/v1/orgs/me >/dev/null 2>&1; do
  i=$((i + 1)); [ "$i" -gt 90 ] && { echo "[zitadel-init] API not ready, abort"; exit 1; }
  sleep 2
done

name_query() { printf '{"queries":[{"nameQuery":{"name":"%s","method":"TEXT_QUERY_METHOD_EQUALS"}}]}' "$1"; }

# --- Project ---
PID="$(api POST /management/v1/projects/_search "$(name_query mindstock)" | jq -r '.result[0].id // empty')"
if [ -z "$PID" ]; then
  PID="$(api POST /management/v1/projects '{"name":"mindstock"}' | jq -r '.id')"
  echo "[zitadel-init] created project mindstock = $PID"
else
  echo "[zitadel-init] reuse project mindstock = $PID"
fi

# --- API app (mindstock-backend) ---
API_CID="$(api POST "/management/v1/projects/$PID/apps/_search" "$(name_query mindstock-backend)" \
  | jq -r '.result[0].apiConfig.clientId // empty')"
if [ -z "$API_CID" ]; then
  API_CID="$(api POST "/management/v1/projects/$PID/apps/api" \
    '{"name":"mindstock-backend","authMethodType":"API_AUTH_METHOD_TYPE_PRIVATE_JWT"}' | jq -r '.clientId')"
  echo "[zitadel-init] created API app = $API_CID"
else
  echo "[zitadel-init] reuse API app = $API_CID"
fi

# --- PKCE app (mindstock-frontend) ---
FE_CID="$(api POST "/management/v1/projects/$PID/apps/_search" "$(name_query mindstock-frontend)" \
  | jq -r '.result[0].oidcConfig.clientId // empty')"
if [ -z "$FE_CID" ]; then
  FE_CID="$(api POST "/management/v1/projects/$PID/apps/oidc" '{
    "name": "mindstock-frontend",
    "redirectUris": ["http://localhost:8080/auth/callback"],
    "postLogoutRedirectUris": ["http://localhost:8080/"],
    "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
    "grantTypes": ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
    "appType": "OIDC_APP_TYPE_USER_AGENT",
    "authMethodType": "OIDC_AUTH_METHOD_TYPE_NONE",
    "devMode": true,
    "accessTokenType": "OIDC_TOKEN_TYPE_JWT",
    "accessTokenRoleAssertion": true
  }' | jq -r '.clientId')"
  echo "[zitadel-init] created PKCE app = $FE_CID"
else
  echo "[zitadel-init] reuse PKCE app = $FE_CID"
fi

# --- 書き出し ---
cat > "$OUT" <<EOF
# generated by docker/zitadel-init.sh on \`docker compose up\` — DO NOT edit by hand.
# backend(:backend:api:run)/ frontend(:frontend:wasmJsBrowserDevelopmentRun)の両方で読み込む。
AUTH_ISSUER=http://localhost:8081
AUTH_JWKS_URL=http://localhost:8081/oauth/v2/keys
AUTH_PROJECT_ID=$PID
AUTH_AUDIENCE=$API_CID
AUTH_CLIENT_ID=$FE_CID
AUTH_REDIRECT_URI=http://localhost:8080/auth/callback
AUTH_POST_LOGOUT_REDIRECT_URI=http://localhost:8080/
EOF

echo "[zitadel-init] wrote $OUT :"
cat "$OUT"
echo "[zitadel-init] done. login: admin@localhost / Password1!"
